name: C/C++ CI

on:
  push:
  schedule:
    - cron: '0 0 */7 * *'

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v5

    - name: Install dependencies
      run: pip3 install -U online-judge-verify-helper

    - name: Set up cache
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/online-judge-tools
          .verify-helper/timestamps.remote.json
        key: verify-${{ github.run_number }}-${{ github.run_attempt }}
        restore-keys: verify-

    - name: Run tests
      env:
        YUKICODER_TOKEN: ${{ secrets.YUKICODER_TOKEN }}
        DROPBOX_TOKEN: ${{ secrets.DROPBOX_TOKEN }}
      run: oj-verify run

    - name: Log timestamps
      run: cat .verify-helper/timestamps.remote.json

  stress:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
    - uses: actions/checkout@v4

    - name: Run tests
      run: make test

